#!/bin/bash
# Script to compile and execute a c program in one step.

 

numA=1000
numB=1000
numL=10000
numT=4
# Compile the program with -o option to specify the name of the binary
gcc   -o serial omp_0.c
gcc -fopenmp -o EXECtask1 omp_1.c
gcc -fopenmp -o EXECtask2 omp_2.c
gcc -fopenmp -o EXECtask3 omp_3.c


# If there were no compilation errors, run the program
echo "-------------------------------------------------------------------------------------------------------"
echo "*********************************************************"
echo "******************** SERIAL PROGRAM *********************"
echo "*********************************************************"
./serial <<EOF

$numA

$numB

$numL

EOF
#(echo "$numA"; echo "$numB"; echo "$numL" )| ./serial

echo "-------------------------------------------------------------------------------------------------------"
echo "*********************************************************"
echo "******************** OPENMP - TASK1 *********************"
echo "*********************************************************"
./EXECtask1 <<EOF

$numA

$numB

$numL

$numT

EOF
echo "-------------------------------------------------------------------------------------------------------"
echo "*********************************************************"
echo "******************** OPENMP - TASK2 *********************"
echo "*********************************************************"
./EXECtask2 <<EOF

$numA

$numB

$numL

$numT

EOF
echo "-------------------------------------------------------------------------------------------------------"
echo "*********************************************************"
echo "******************** OPENMP - TASK3 *********************"
echo "*********************************************************"
./EXECtask3 <<EOF

$numA

$numB

$numL

$numT

EOF

#./EXECtask3 <<< "$numA $numB $numL $numT"
